// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleGax

/// The Cloud API Registry service provides a central registry for managing API
/// Data.
///
/// @Snippet(path: "CloudApiRegistryQuickstart")
public final class CloudApiRegistryClient: Clients.CloudApiRegistryProtocol, Sendable {
  let inner: any Clients.CloudApiRegistryStub

  /// Creates a new `CloudApiRegistryClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.CloudApiRegistryStub = try Clients.CloudApiRegistryTransport(options)
    inner = Clients.CloudApiRegistryRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CloudApiRegistryLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Gets a single McpServer.
  ///
  /// @Snippet(path: "CloudApiRegistry_GetMcpServer")
  public func getMcpServer(
    request: GetMcpServerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiRegistryV1.McpServer {
    try await self.inner.getMcpServer(request: request, options: options)
  }

  /// Lists McpServers in a given Project.
  ///
  /// @Snippet(path: "CloudApiRegistry_ListMcpServers")
  public func listMcpServers(
    request: ListMcpServersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiRegistryV1.ListMcpServersResponse {
    try await self.inner.listMcpServers(request: request, options: options)
  }

  /// Gets a single McpTool.
  ///
  /// @Snippet(path: "CloudApiRegistry_GetMcpTool")
  public func getMcpTool(
    request: GetMcpToolRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiRegistryV1.McpTool {
    try await self.inner.getMcpTool(request: request, options: options)
  }

  /// Lists McpTools in a given McpServer.
  ///
  /// @Snippet(path: "CloudApiRegistry_ListMcpTools")
  public func listMcpTools(
    request: ListMcpToolsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiRegistryV1.ListMcpToolsResponse {
    try await self.inner.listMcpTools(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CloudApiRegistry_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "CloudApiRegistry_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CloudApiRegistryClient`.
  ///
  /// To mock `CloudApiRegistryClient` change your functions to receive
  /// `some CloudApiRegistryProtocol` or `any CloudApiRegistryProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CloudApiRegistryProtocol: Sendable {
    /// See `CloudApiRegistryClient.getMcpServer`.
    func getMcpServer(
      request: GetMcpServerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiRegistryV1.McpServer

    /// See `CloudApiRegistryClient.listMcpServers`.
    func listMcpServers(
      request: ListMcpServersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiRegistryV1.ListMcpServersResponse

    /// See `CloudApiRegistryClient.getMcpTool`.
    func getMcpTool(
      request: GetMcpToolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiRegistryV1.McpTool

    /// See `CloudApiRegistryClient.listMcpTools`.
    func listMcpTools(
      request: ListMcpToolsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiRegistryV1.ListMcpToolsResponse

    /// See `CloudApiRegistryClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `CloudApiRegistryClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}

// Default implementations
extension Clients.CloudApiRegistryProtocol {
  public func getMcpServer(request: GetMcpServerRequest) async throws
    -> GoogleCloudApiRegistryV1.McpServer
  {
    try await self.getMcpServer(request: request, options: .init())
  }

  public func getMcpServer(
    request: GetMcpServerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiRegistryV1.McpServer {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getMcpServer(
    name: Swift.String,
  ) async throws -> GoogleCloudApiRegistryV1.McpServer {
    let request = GetMcpServerRequest().with {
      $0.name = name
    }
    return try await self.getMcpServer(request: request)
  }

  public func listMcpServers(request: ListMcpServersRequest) async throws
    -> GoogleCloudApiRegistryV1.ListMcpServersResponse
  {
    try await self.listMcpServers(request: request, options: .init())
  }

  public func listMcpServers(
    request: ListMcpServersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiRegistryV1.ListMcpServersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listMcpServersByItems(
    request: ListMcpServersRequest
  ) -> any AsyncSequence<McpServer, Swift.Error> & Sendable {
    self.listMcpServersByItems(request: request, options: .init())
  }

  /// Lists McpServers in a given Project.
  ///
  /// @Snippet(path: "CloudApiRegistry_ListMcpServers")
  public func listMcpServersByItems(
    request: ListMcpServersRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<McpServer, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudApiRegistryV1.ListMcpServersResponse in
      var request = request
      request.pageToken = token
      return try await self.listMcpServers(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listMcpServersByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<McpServer, Swift.Error> & Sendable {
    let request = ListMcpServersRequest().with {
      $0.parent = parent
    }
    return self.listMcpServersByItems(request: request)
  }

  public func getMcpTool(request: GetMcpToolRequest) async throws
    -> GoogleCloudApiRegistryV1.McpTool
  {
    try await self.getMcpTool(request: request, options: .init())
  }

  public func getMcpTool(
    request: GetMcpToolRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiRegistryV1.McpTool {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getMcpTool(
    name: Swift.String,
  ) async throws -> GoogleCloudApiRegistryV1.McpTool {
    let request = GetMcpToolRequest().with {
      $0.name = name
    }
    return try await self.getMcpTool(request: request)
  }

  public func listMcpTools(request: ListMcpToolsRequest) async throws
    -> GoogleCloudApiRegistryV1.ListMcpToolsResponse
  {
    try await self.listMcpTools(request: request, options: .init())
  }

  public func listMcpTools(
    request: ListMcpToolsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiRegistryV1.ListMcpToolsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listMcpToolsByItems(
    request: ListMcpToolsRequest
  ) -> any AsyncSequence<McpTool, Swift.Error> & Sendable {
    self.listMcpToolsByItems(request: request, options: .init())
  }

  /// Lists McpTools in a given McpServer.
  ///
  /// @Snippet(path: "CloudApiRegistry_ListMcpTools")
  public func listMcpToolsByItems(
    request: ListMcpToolsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<McpTool, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudApiRegistryV1.ListMcpToolsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listMcpTools(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listMcpToolsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<McpTool, Swift.Error> & Sendable {
    let request = ListMcpToolsRequest().with {
      $0.parent = parent
    }
    return self.listMcpToolsByItems(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CloudApiRegistry_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }
}
