// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents an MCP Server. MCP Servers act as endpoints that expose a
/// collection of tools that can be invoked by agents.
public struct McpServer: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the MCP Server.
  /// Format:
  /// `projects/{project}/locations/{location}/mcpServers/{mcp_server}`.
  /// Example:
  /// projects/12345/locations/us-central1/mcpServers/google:bigquery.googleapis.com:mcp
  /// for 1p
  /// projects/12345/locations/us-central1/mcpServers/apphub:starbucks for
  /// 2p
  public var name: Swift.String = Swift.String()

  /// Optional. A human readable name for the MCP server.
  public var displayName: Swift.String = Swift.String()

  /// Optional. A human-readable description of the MCP Server's functionality.
  public var description: Swift.String = Swift.String()

  /// The base URL of the MCP server. Example: [geolocation.googleapis.com/mcp].
  public var urls: [Swift.String] = []

  /// The capabilities that a server may support. Known capabilities defined in
  /// https://modelcontextprotocol.io/specification/2025-06-18/schema#servercapabilities
  /// and additional capabilities defined by the servers.
  public var capabilities: GoogleWKT.WKTStruct? = nil

  /// Output only. The state of the MCP Server.
  public var state: State = State()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `McpServer`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = McpServer().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let urls = CodingKeys(stringValue: "urls")
    static let capabilities = CodingKeys(stringValue: "capabilities")
    static let state = CodingKeys(stringValue: "state")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "description",
      "urls",
      "capabilities",
      "state",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .urls) {
      self.urls = value
    }
    self.capabilities = try container.decodeIfPresent(
      GoogleWKT.WKTStruct.self, forKey: .capabilities)
    if let value = try container.decodeIfPresent(State.self, forKey: .state) {
      self.state = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.urls, forKey: .urls)
    try container.encodeIfPresent(self.capabilities, forKey: .capabilities)
    try container.encode(self.state, forKey: .state)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apiregistry.v1.McpServer"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
