// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing McpTool object
public struct McpTool: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the McpTool.
  /// Format:
  /// `projects/{project}/locations/{location}/mcpServers/{mcp_server}/mcpTools/{mcp_tool}`.
  /// Example:
  /// projects/12345/locations/us-central1/mcpServers/google:bigquery.googleapis.com:mcp/mcpTools/insert_job
  /// for 1p
  /// projects/12345/locations/us-central1/mcpServers/apphub:starbucks/mcpTools/order_pizza
  /// for 2p
  public var name: Swift.String = Swift.String()

  /// Optional. A human-readable name for the tool, suitable for display.
  public var displayName: Swift.String = Swift.String()

  /// A human-readable description of the tool's functionality.
  public var description: Swift.String = Swift.String()

  /// Automatically populated reference to MCP Server. Helpful when multiple
  /// tools are requested across different MCP Servers.
  public var mcpServerUrls: [Swift.String] = []

  /// A JSON Schema object defining the expected parameters for invoking the
  /// tool.
  public var inputSchema: GoogleWKT.WKTStruct? = nil

  /// Optional. A JSON Schema object defining the expected structure of the
  /// tool's output.
  public var outputSchema: GoogleWKT.WKTStruct? = nil

  /// Optional key-value object that allows developers to provide additional
  /// information regarding tool properties, behavior, and usage best practices.
  /// Annotations or tags to facilitate semantic search across tools ("semantic
  /// tags") are not in the MVP scope. When implemented, the first set of
  /// supported annotations will likely be the standard, predefined annotations
  /// from the open-source MCP spec. These include:
  ///   - title: A human-readable title for the tool, useful for UI display.
  ///   - readOnlyHint: If true, indicates the tool does not modify its
  ///   environment.
  ///   - destructiveHint: If true, the tool may perform destructive updates
  ///   (only meaningful when readOnlyHint is false).
  ///   - idempotentHint: If true, calling the tool repeatedly with the same
  ///   arguments has no additional effect (only meaningful when readOnlyHint is
  ///   false).
  ///   - openWorldHint: If true, the tool may interact with an "open world" of
  ///   external entities.
  public var annotations: GoogleWKT.WKTStruct? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `McpTool`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = McpTool().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let mcpServerUrls = CodingKeys(stringValue: "mcpServerUrls")
    static let inputSchema = CodingKeys(stringValue: "inputSchema")
    static let outputSchema = CodingKeys(stringValue: "outputSchema")
    static let annotations = CodingKeys(stringValue: "annotations")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "description",
      "mcpServerUrls",
      "inputSchema",
      "outputSchema",
      "annotations",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .mcpServerUrls) {
      self.mcpServerUrls = value
    }
    self.inputSchema = try container.decodeIfPresent(GoogleWKT.WKTStruct.self, forKey: .inputSchema)
    self.outputSchema = try container.decodeIfPresent(
      GoogleWKT.WKTStruct.self, forKey: .outputSchema)
    self.annotations = try container.decodeIfPresent(GoogleWKT.WKTStruct.self, forKey: .annotations)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.mcpServerUrls, forKey: .mcpServerUrls)
    try container.encodeIfPresent(self.inputSchema, forKey: .inputSchema)
    try container.encodeIfPresent(self.outputSchema, forKey: .outputSchema)
    try container.encodeIfPresent(self.annotations, forKey: .annotations)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apiregistry.v1.McpTool"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
